name: Build Theme Assets

on:
  push:
    branches:
      - main
      - 'cursor/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Build CSS assets
        run: npm run build:css
        continue-on-error: true
      
      - name: Commit built assets
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add theme/assets/theme.css || true
          git diff --staged --quiet || git commit -m "chore: build theme assets [skip ci]"
          git push || true
        continue-on-error: true
      
      - name: Upload theme artifact
        uses: actions/upload-artifact@v3
        with:
          name: theme-build
          path: theme/
          retention-days: 30
